spring:
  application:
    name: game-keeper
kafka:
  producer:
    bootstrap-servers: localhost:9092
    topic: gkeeper-input-topic
  consumer:
    bootstrap-servers: localhost:9092
    group-id: gkeeper-group
    topic: gkeeper-output-topic
  streams:
    application-id: game-keeper-application
    bootstrap-servers: localhost:9092
    input-topic: gkeeper-input-topic
    output-topic: gkeeper-output-topic
